// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// classification_metrics
List classification_metrics(CharacterVector predicted, CharacterVector truth, CharacterVector classes, double rare_threshold);
RcppExport SEXP _thisutils_classification_metrics(SEXP predictedSEXP, SEXP truthSEXP, SEXP classesSEXP, SEXP rare_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type predicted(predictedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type classes(classesSEXP);
    Rcpp::traits::input_parameter< double >::type rare_threshold(rare_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(classification_metrics(predicted, truth, classes, rare_threshold));
    return rcpp_result_gen;
END_RCPP
}
// sparse_topk_by_column
List sparse_topk_by_column(S4 mat, int k, bool decreasing);
RcppExport SEXP _thisutils_sparse_topk_by_column(SEXP matSEXP, SEXP kSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_topk_by_column(mat, k, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// dense_topk_by_column
List dense_topk_by_column(NumericMatrix mat, int k, bool decreasing);
RcppExport SEXP _thisutils_dense_topk_by_column(SEXP matSEXP, SEXP kSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(dense_topk_by_column(mat, k, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// compute_lisi_matrix
NumericMatrix compute_lisi_matrix(const NumericMatrix& X, const IntegerMatrix& batch_labels, int n_neighbors, double perplexity, double tol, int max_iter);
RcppExport SEXP _thisutils_compute_lisi_matrix(SEXP XSEXP, SEXP batch_labelsSEXP, SEXP n_neighborsSEXP, SEXP perplexitySEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type batch_labels(batch_labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< double >::type perplexity(perplexitySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_lisi_matrix(X, batch_labels, n_neighbors, perplexity, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// lisi_exact_knn_cpp
List lisi_exact_knn_cpp(const NumericMatrix& X, int k, bool exclude_self);
RcppExport SEXP _thisutils_lisi_exact_knn_cpp(SEXP XSEXP, SEXP kSEXP, SEXP exclude_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type exclude_self(exclude_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(lisi_exact_knn_cpp(X, k, exclude_self));
    return rcpp_result_gen;
END_RCPP
}
// drop_self_from_knn_cpp
List drop_self_from_knn_cpp(const IntegerMatrix& nn_idx, const NumericMatrix& nn_dists);
RcppExport SEXP _thisutils_drop_self_from_knn_cpp(SEXP nn_idxSEXP, SEXP nn_distsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type nn_dists(nn_distsSEXP);
    rcpp_result_gen = Rcpp::wrap(drop_self_from_knn_cpp(nn_idx, nn_dists));
    return rcpp_result_gen;
END_RCPP
}
// matrix_to_table
DataFrame matrix_to_table(SEXP matrix, SEXP row_names, SEXP col_names, double threshold, bool keep_zero);
RcppExport SEXP _thisutils_matrix_to_table(SEXP matrixSEXP, SEXP row_namesSEXP, SEXP col_namesSEXP, SEXP thresholdSEXP, SEXP keep_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row_names(row_namesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col_names(col_namesSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_zero(keep_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_to_table(matrix, row_names, col_names, threshold, keep_zero));
    return rcpp_result_gen;
END_RCPP
}
// split_indices
std::vector<std::vector<int>> split_indices(IntegerVector group, int n);
RcppExport SEXP _thisutils_split_indices(SEXP groupSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(split_indices(group, n));
    return rcpp_result_gen;
END_RCPP
}
// table_to_matrix
SEXP table_to_matrix(DataFrame table, SEXP row_names, SEXP col_names, double threshold, bool return_sparse);
RcppExport SEXP _thisutils_table_to_matrix(SEXP tableSEXP, SEXP row_namesSEXP, SEXP col_namesSEXP, SEXP thresholdSEXP, SEXP return_sparseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type table(tableSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row_names(row_namesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col_names(col_namesSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type return_sparse(return_sparseSEXP);
    rcpp_result_gen = Rcpp::wrap(table_to_matrix(table, row_names, col_names, threshold, return_sparse));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thisutils_classification_metrics", (DL_FUNC) &_thisutils_classification_metrics, 4},
    {"_thisutils_sparse_topk_by_column", (DL_FUNC) &_thisutils_sparse_topk_by_column, 3},
    {"_thisutils_dense_topk_by_column", (DL_FUNC) &_thisutils_dense_topk_by_column, 3},
    {"_thisutils_compute_lisi_matrix", (DL_FUNC) &_thisutils_compute_lisi_matrix, 6},
    {"_thisutils_lisi_exact_knn_cpp", (DL_FUNC) &_thisutils_lisi_exact_knn_cpp, 3},
    {"_thisutils_drop_self_from_knn_cpp", (DL_FUNC) &_thisutils_drop_self_from_knn_cpp, 2},
    {"_thisutils_matrix_to_table", (DL_FUNC) &_thisutils_matrix_to_table, 5},
    {"_thisutils_split_indices", (DL_FUNC) &_thisutils_split_indices, 2},
    {"_thisutils_table_to_matrix", (DL_FUNC) &_thisutils_table_to_matrix, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_thisutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
